name: Scraping Tasks

on:
  schedule:
    - cron: '11 1,3,6,7,9,12 * * *'  # talent_tickets: JST 10:11, 12:11, 15:11, 16:11, 18:31, 21:31
    - cron: '21 1,3,6,7,9,12 * * *'  # theater_schedules: JST 10:21, 12:21, 15:21, 16:21, 18:41, 21:41
    - cron: '30 1,3,6,7,9,12 * * *'  # merge_events: JST 10:30, 12:30, 15:30, 16:30, 18:50, 21:50
    - cron: '15 9 * * *'  # mypage_tickets: JST 18:15
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest

    environment: 
      name: config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          echo "TALENT_BASE_URL=${{ vars.TALENT_BASE_URL }}" >> $GITHUB_ENV
          printf "TALENTS=%s\n" "$(echo '${{ vars.TALENTS }}' | jq -c .)" >> $GITHUB_ENV
          printf "THEATERS=%s\n" "$(echo '${{ vars.THEATERS }}' | jq -c .)" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "TALENT_BASE_URL=${{ env.TALENT_BASE_URL }}"
          echo "TALENTS=${{ env.TALENTS }}"
          echo "THEATERS=${{ env.THEATERS }}"

      - name: Set environment variables based on schedule
        run: |
          if [[ "${{ github.event.schedule }}" == "30 1,3,6,7,9,12 * * *" ]]; then
            echo "RUN_MERGE=true" >> $GITHUB_ENV
          else
            echo "RUN_MERGE=false" >> $GITHUB_ENV
          fi
          if [[ "${{ github.event.schedule }}" == "15 9 * * *" ]]; then
            echo "RUN_MERGE=true" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Install Python dependencies (only for mypage)
        if: env.RUN_MERGE == 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pandas

      - name: Debug Installed Packages (only for mypage)
        if: env.RUN_MERGE == 'true'
        run: |
          python3 -c "import pandas; print('pandas installed successfully')"

      - name: Run talent tickets scraping
        run: node talent_tickets.js
        if: github.event.schedule == '11 1,3,6,7,9,12 * * *'

      - name: Run theater schedules scraping
        run: node theater_schedules.js
        if: github.event.schedule == '21 1,3,6,7,9,12 * * *'

      # - name: Run merge_events
      #   run: python3 merge_events.py
      #   if: github.event.schedule == '30 1,3,6,7,9,12 * * *'

      - name: Run mypage tickets scraping
        run: node mypage_tickets.js
        if: github.event.schedule == '15 9 * * *'

      - name: Commit & Push results
        env:
          GH_PAT: ${{ secrets.GH_FUNNY_PAT }}
        run: |
          echo "https://x-access-token:${GH_PAT}@github.com/"
          echo "https://x-access-token:${{ env.GH_PAT }}@github.com/"
          
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add *.json
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push https://x-access-token:${{ env.GH_PAT }}@github.com/ykyk-314/funny-event-scraper.git
