name: Scraping Tasks

on:
  schedule:
    - cron: '11 1,3,6,7,9,12 * * *'  # talent_tickets: JST 10:11, 12:11, 15:11, 16:11, 18:31, 21:31
    - cron: '21 1,3,6,7,9,12 * * *'  # theater_schedules: JST 10:21, 12:21, 15:21, 16:21, 18:41, 21:41
    - cron: '30 1,3,6,7,9,12 * * *'  # merge_events: JST 10:30, 12:30, 15:30, 16:30, 18:50, 21:50
    - cron: '15 9 * * *'  # mypage_tickets: JST 18:15
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest
    env:
      TALENT_BASE_URL: ${{ vars.TALENT_BASE_URL }}
      TALENTS: ${{ vars.TALENTS }}
      THEATERS: ${{ vars.THEATERS }}
      MYF_LOGIN_ID: ${{ secrets.MYF_LOGIN_ID }}
      MYF_LOGIN_PW: ${{ secrets.MYF_LOGIN_PW }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Environment Variables
        env:
          THEATERS: ${{ vars.THEATERS }}
        run: |
          echo "THEATERS=${THEATERS}"

      - name: Set environment variables based on schedule
        run: |
          if [[ "${{ github.event.schedule }}" == "30 1,3,6,7,9,12 * * *" ]]; then
            echo "RUN_MERGE=true" >> $GITHUB_ENV
          else
            echo "RUN_MERGE=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Install Python dependencies (only for mypage)
        if: env.RUN_MERGE == 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pandas

      - name: Debug Installed Packages (only for mypage)
        if: env.RUN_MERGE == 'true'
        run: |
          python3 -c "import pandas; print('pandas installed successfully')"

      - name: Run talent tickets scraping
        env:
          TALENT_BASE_URL: ${{ vars.TALENT_BASE_URL }}
          TALENTS: ${{ vars.TALENTS }}
        run: node talent_tickets.js
        if: github.event.schedule == '11 1,3,6,7,9,12 * * *'

      - name: Run theater schedules scraping
        env:
          THEATERS: ${{ vars.THEATERS }}
        run: node theater_schedules.js
        if: github.event.schedule == '21 1,3,6,7,9,12 * * *'

      # - name: Run merge_events
      #   run: python3 merge_events.py
      #   if: github.event.schedule == '30 1,3,6,7,9,12 * * *'

      # - name: Run mypage tickets scraping
      #   run: node mypage_tickets.js
      #   if: github.event.schedule == '15 9 * * *'

      - name: DEBUG GIT
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
        run: |
          echo "THEATERS=${GIT_EMAIL}"

      - name: Commit & Push results
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
        run: |
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_USER}"
          git add *.json
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
