name: Scraping Tasks

on:
  schedule:
    - cron: '11 1,3,6,7,9,12 * * *'  # talent_tickets: JST 10:11, 12:11, 15:11, 16:11, 18:31, 21:31
    - cron: '21 1,3,6,7,9,12 * * *'  # theater_schedules: JST 10:21, 12:21, 15:21, 16:21, 18:41, 21:41
    - cron: '30 1,3,6,7,9,12 * * *'  # merge_events: JST 10:30, 12:30, 15:30, 16:30, 18:50, 21:50
    - cron: '15 9 * * *'  # mypage_tickets: JST 18:15

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Run talent tickets scraping
        run: node talent_tickets.js
        if: github.event.schedule == '11 1,3,6,7,9,12 * * *'

      - name: Run theater schedules scraping
        run: node theater_schedules.js
        if: github.event.schedule == '21 1,3,6,7,9,12 * * *'

      - name: Run merge_events
        run: python3 merge_events.py
        if: github.event.schedule == '30 1,3,6,7,9,12 * * *'

      - name: Run mypage tickets scraping
        run: node mypage_tickets.js
        if: github.event.schedule == '15 9 * * *'

      - name: Commit & Push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.json
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
